
services:
  postgres:
    image: postgres:16
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=pruebatecnicarym
      - POSTGRES_USER=Carlos
      - POSTGRES_DB=PruebaRickAndMorty
    networks:
      - pruebatecnica

networks:
  pruebatecnica: